# 定制类

[TOC]

## \__str__()函数

用于输出实例对象信息的字符串，使用方法如下：

```python
class People(object):
	def __init__(self,name):
		self.name = name
	def __str__(self):
		return '\'People-type\'instance with an attribute \'name\':%s'%self.name
Li = People('LZ')
print(Li)
```

## 工厂函数

list(), int(),long(),str(),tuple()等等通过一个函数而不是通过一个类创建一个对象（实例化）

## \_\_call\_\_()函数

如果定义了该函数，则可以把实例当做函数使用。并可以增加参数，添加逻辑。

> `__call__()`还可以定义参数。对实例进行直接调用就好比对一个函数进行调用一样，完全可以把对象看成函数，把函数看成对象，因为这两者之间本来就没根本的区别。
>
> 如果你把对象看成函数，那么函数本身其实也可以在运行期动态创建出来，因为类的实例都是运行期创建出来的，这么一来，我们就模糊了对象和函数的界限。
>
> 通过`callable()`函数，就可以判断一个对象是否是“可调用”对象。

```python
class People(object):
#class for test
	def __init__(self,name):
		self.name = name
    #class attribute for test
	def __call__(self,times):
    #'__call__()' function with a parameter 'times'
		for i in range(times):
			print('I am : '+self.name.upper()+'!')
zhang = People('zhang')
zhang(5)
>>>
I am : ZHANG!
I am : ZHANG!
I am : ZHANG!
I am : ZHANG!
I am : ZHANG!
```

若不定义\_\_call\_\_()函数，则`TypeError: 'People' object is not callable`

## \_\_getitem\_\_()

作用是拦截索引运算符。即如果类继承了这个方法，那么该类的实例I，并出现I[i]（实例[迭代值]）的时候，Python会调用该方法，并将实例本身作为第一参数(self)，`i`作为第二参数传入。

当遇到X[i]时，迭代器环境会先尝试`__iter__()`方法，再尝试`__getitem__()`.也就是如果对象不支持迭代协议，就会尝试索引运算，但当设定`__iter__() = None`时，则说明该类不可迭代。`xxxx object does not support indexing`

若x是某个类的实例，x[i] 相当于type(x).\_\_getitem\_\_(x, i).

举例：

```python 
   class Test(object):
   #随便定义个类，不需要迭代类
   		def __getitem__(self,i):
      		return i*3
   print(Test()[1])
#答案是3,只不过是把[]里的值传入__getitem__()中。
```

## 斐波那契数列的\_\_getitem\_\_()实现

```python
class Fib(object): #只返回制定值
	def __init__(self):
		self.a,self.b = 1,1
	def __getitem__(self,n):
		for i in range(n):
			self.a,self.b = self.b,self.a+self.b
		return self.a
def fib(n):
	X = Fib()
	print(X[n])
fib(5) 
#按顺序打印
class F  ib(object):
	def __init__(self):
		self.a, self.b = 0,1
	def __getitem__(self,n):
		for i in range(n):
			print('No.%s:'%(i+1),self.b)
			self.a, self.b = self.b, self.a + self.b
def fib(n):
	x = Fib()
	x[n] #此处不一样

fib(10)
```



方标式使用

```
X = Fib()
print(x[5])
```

## \_\_getattr__(self, attr_name)函数和\_\_getattribute\_\_(self,attr_name)函数

前者是找不到所需属性时调用，相当于一个容错机制。后者是无论什么时候，不论是否有这个属性都要调用。若没实现前者，调用一个不存在的属性时就会引发AttributeError。当使用类，而不是实例访问不存在的属性时，不会经过\_\_getattr\_\_()函数，依然会报错。

```python
#__getattr__()举例 0129
class C(object):
	a = 'abc'
    #类属性C.a
	def __getattr__(self,attr):
    #当没有相关属性时，调用该方法
    #注意不能写成self.attr == ...,因为实例没有attr属性，又开始调用__getattr__()方法，无限循环下去。
		if attr == 'hi':
			return('Hello')
		else:
			return('Wow!')
X=C()
print(X.hi) 
#访问不存在的属性'hi',进入__getattr()__的if attr == 'hi',Hello！
print(X.a) 
#用实例访问类属性，a，abc
print(X.b) #Wow
#实例访问不存在的属性，进入else
print(C.b) 
#访问不存在的类属性，不调用__getattr__()方法，报错
```

\_\_getattribute\_\_(self, name)函数: 当要取得属性时一定会执行的函数。

### code 1: 一个毫无实际意义的实验例子

```python
class C(object):#测试用类
	a = 'abc' #类属性
	def __init__(self,name):
	    self.name = name
    #实例属性name
	def __getattribute__(self,att_name):
    #定义该函数，只打印一句话，无返回值
		print('getattribute is called!')
c1=C('test') #创建实例c1
print(c1.name) 
#尝试获取实例属性，调用__getattribute__函数
#打印'getattribute is called!'和返回值None.没有返回值则默认返回None.
```

上述实验因为没有返回所尝试获取的属性，因而是没有意义的，所以要在\__getattribute__内部加入返回属性的语句。这里和getattr一样，若直接返回属性本身则会陷入无限循环。所以要返回父类的该方法值.

> In order to avoid infinite recursion in this method, its implementation should always call the base class method with the same name to access any attributes it needs, for example,object.\_\_getattribute\_\_(self, name)

### code 2: 如何返回所需的属性。

```python
class C(object):
	a = 'abc'
	def __init__(self,name):
	    self.name = name
	def __getattribute__(self,att_name):
		print('getattribute is called!')
		#return self.att_name 直接这么写就无限循环了。
        return object.__getattribute__(self,att_name)
c1=C('test')
print(c1.name)
#'getattribute is called!'
#test
```

### code 3: 两个函数同时存在的情况

~~如果同时定义了\_\_getattribute\_\_()和\_\_getattr\_\_()函数，那么除非明确调用或模仿原本的行为抛出AttributeError，那么后者不会被调用。~~

```python
class C(object):
	a = 'abc'
	def __init__(self,name):
	    self.name = name
	def __getattribute__(self,att_name):
		print('getattribute is called!')
		print()
		return object.__getattribute__(self,att_name)
		
	def __getattr__(self,att_name):
		print('getattr is called')
		return('no such attribute')
c1=C('test')
print(c1.haha)
```

答案是

> getattribute is called!
>
> getattr is called
>
> no such attribute

尝试使用不存在的属性，即抛出AttributeError，则两个函数都被调用了。但如果在第一个函数中加入捕获AttributeError，那么第二个就不会调用，

### code 4: 捕获AttributeError的getattributeh函数

```python
class C(object):
	a = 'abc'
	def __init__(self,name):
	    self.name = name
	def __getattribute__(self,att_name):
		try:
			print('getattribute is called!')
			return object.__getattribute__(self,att_name)
		except AttributeError:
			return('NO SUCH ATTRIBUTE AS \'%s\''%att_name)
		
	def __getattr__(self,att_name):
		print('getattr is called')
		return('no such attribute')
c1=C('test')
print(c1.haha)
```

> getattribute is called!
> NO SUCH ATTRIBUTE AS 'haha'

可以将\_\_getattr\_\_()函数看做是捕获AttribueError的函数。

